---
apiVersion: v1
kind: Service
metadata:
  name: monitor-service-server
  namespace: default
spec:
  selector:
    app: monitor-service
  ports:
    - protocol: TCP
      port: 8040
      name: monitorport
  type: ClusterIP
