#apiVersion: apps/v1beta1
#kind: Deployment
#metadata:
#  name: admin-gateway-deployment
#spec:
#  replicas: 1
#  template: 
#    metadata:
#      labels:
#        app: admin-gateway
#    spec:
#      containers:
#      - name: admin-gateway
#        image: harbor.mofangge.net/sit/common-services:sit
#        imagePullPolicy: Always
#        env:
#          - name: JAVA_OPTS
#            value: "-Dspring.profiles.active=test -Dapollo.meta=http://service-apollo-config-server-test-alpha.sre:8080"
#        ports:
#        - containerPort: 8002
#          containerPort: 8502


#后台管理网关
---
apiVersion: v1
kind: Service
metadata:
  name: admin-gateway-server
  namespace: default
spec:
  selector:
    app: admin-gateway
  ports:
    - protocol: TCP
      port: 8002
      name: gwport
    - protocol: TCP
      port: 8502
      name: adminport
  type: ClusterIP

---
