---
apiVersion: v1
kind: Service
metadata:
  name: sleuth-zipkin-service-server
  namespace: default
spec:
  selector:
    app: sleuth-zipkin-service
  ports:
    - protocol: TCP
      port: 9411
      name: sleuthport
    - protocol: TCP
      port: 9412
      name: sleuth2port
  type: ClusterIP
