---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: xxl-job-deployment
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: xxl-job
    spec:
      containers:
      - name: xxl-job
        image: xuxueli/xxl-job-admin:2.0.1
        imagePullPolicy: Always
        env:
          - name: PARAMS
            value: "--spring.datasource.url=jdbc:mysql://steam-mysql57.mysql.rds.aliyuncs.com:3306/xxl-job?useLegacyDatetimeCode=false&serverTimezone=Asia/Hong_Kong&useSSL=false --spring.datasource.username=ymsteam --spring.datasource.password=Ymsteam@Yxsd"
        ports:
        - containerPort: 8080

