
---
# configmap for apollo-config-server-test-alpha
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: sre
  name: configmap-apollo-config-server-test-alpha
data:
  application-github.properties: |
    spring.datasource.url = jdbc:mysql://steam-mysql57.mysql.rds.aliyuncs.com:3306/ApolloConfigDB?characterEncoding=utf8
    spring.datasource.username = apollo
    spring.datasource.password = Apollo@Yxsd

---
kind: Service
apiVersion: v1
metadata:
  namespace: sre
  name: service-apollo-meta-server-test-alpha
  labels:
    app: service-apollo-meta-server-test-alpha
spec:
  ports:
    - protocol: TCP
      port: 8080
  selector:
    app: pod-apollo-config-server-test-alpha
  type: ClusterIP

---
kind: StatefulSet
apiVersion: apps/v1beta2
metadata:
  namespace: sre
  name: statefulset-apollo-config-server-test-alpha
  labels:
    app: statefulset-apollo-config-server-test-alpha
spec:
  serviceName: service-apollo-meta-server-test-alpha
  replicas: 2
  selector:
    matchLabels:
      app: pod-apollo-config-server-test-alpha
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pod-apollo-config-server-test-alpha
    spec:
      nodeName: cn-beijing.i-2zec8yxlrlzhkl9uzrtq
      
      volumes:
        - name: volume-configmap-apollo-config-server-test-alpha
          configMap:
            name: configmap-apollo-config-server-test-alpha
            items:
              - key: application-github.properties
                path: application-github.properties
      imagePullSecrets:
        - name: vpc-registry-secret-apollo
      containers:
        - image: registry-vpc.cn-beijing.aliyuncs.com/yxsd/apollo-configservice:sit
          resources: 
            requests: 
              memory: "256Mi"
            limits:
              memory: "1024Mi" 
          securityContext:
            privileged: true
          imagePullPolicy: IfNotPresent
          name: container-apollo-config-server-test-alpha
          ports:
            - protocol: TCP
              containerPort: 8080
          env:
            - name: APOLLO_CONFIG_SERVICE_NAME
              value: "service-apollo-config-server-test-alpha.sre"
          
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
          
      dnsPolicy: ClusterFirst
      restartPolicy: Always
