apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: admin-auth-server-deployment
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: admin-auth-server
    spec:
      imagePullSecrets:
        - name: vpc-registry-secret
      containers:
      - name: admin-auth-server
        image: registry-vpc.cn-beijing.aliyuncs.com/yxsd/admin-auth-server:pro
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTS
            value: "-server -Xms1024m -Xmx1024m -Xss256k -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=384m -XX:SurvivorRatio=8 -Dspring.profiles.active=prod -Dapollo.meta=http://service-apollo-meta-server-test-alpha.sre:8080"
        ports:
        - containerPort: 8003
          containerPort: 8503
