apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: grammarback-patent-deployment
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: grammarback-patent
    spec:
      imagePullSecrets:
        - name: vpc-registry-secret
      containers:
      - name: grammarback-patent
        image: registry-vpc.cn-beijing.aliyuncs.com/yxsd/grammarback-patent:pro
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTS
            value: "-server -Xms1024m -Xmx1024m -Xss256k -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=384m -XX:SurvivorRatio=8  -Dspring.profiles.active=prod"
        ports:
        - containerPort: 7010
