apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pay-center-service-deployment
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: pay-center-service
    spec:
      imagePullSecrets:
        - name: vpc-registry-secret
      containers:
      - name: pay-center-service
        image: registry-vpc.cn-beijing.aliyuncs.com/yxsd/pay-center-service:pro
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTS
            value: "-server -Xms1024m -Xmx1024m -Xss256k -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=384m -XX:SurvivorRatio=8  -Dspring.profiles.active=prod  -Dapollo.meta=http://service-apollo-meta-server-test-alpha.sre:8080"
        ports:
        - containerPort: 7110
          containerPort: 9110
---
apiVersion: v1
kind: Service
metadata:
  name: pay-center-service-server
  namespace: default
spec:
  selector:
    app: pay-center-service
  ports:
    - protocol: TCP
      port: 7110
      name: payport
  type: ClusterIP
