---
apiVersion: v1
kind: Service
metadata:
  name: erp-gateway-service
  namespace: default
spec:
  selector:
    app: erp-gateway
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8005
      name: erp-gateway

